workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "schedule"'
      when: always

check_update_commit:
  before_script:
    - git config --global user.name "${GITLAB_USER_NAME}"
    - git config --global user.email "${GITLAB_USER_EMAIL}"
  script:
    - |
      echo "Installing dependencies..."
      curl -sL https://deb.nodesource.com/setup_14.x | bash -
      apt-get update -qq
      apt-get install -y --no-install-recommends nodejs
      npm -v
      node -v
      echo "Checking if there are updates..."
      cd bin && ./update-and-commit